# Generated by Django 6.0.3 on 2026-03-11 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do animal"),
                ),
                (
                    "especie",
                    models.CharField(
                        choices=[("cao", "Cão"), ("gato", "Gato"), ("outro", "Outro")],
                        max_length=20,
                        verbose_name="Espécie",
                    ),
                ),
                (
                    "raca",
                    models.CharField(
                        blank=True,
                        help_text="Deixe em branco para SRD (Sem Raça Definida).",
                        max_length=100,
                        verbose_name="Raça",
                    ),
                ),
                (
                    "idade",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Idade (anos)"
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso em quilogramas. Ex: 12.50",
                        max_digits=5,
                        null=True,
                        verbose_name="Peso (kg)",
                    ),
                ),
                (
                    "queixa",
                    models.TextField(
                        blank=True,
                        help_text="Descreva os sintomas ou motivo do atendimento.",
                        verbose_name="Queixa principal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Animal",
                "verbose_name_plural": "Animais",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Proprietario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome completo do tutor responsável pelo animal.",
                        max_length=200,
                        verbose_name="Nome completo",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        help_text="Número de contato principal. Ex: (19) 99999-9999",
                        max_length=20,
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="E-mail para envio de confirmações (opcional).",
                        max_length=254,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        help_text="CPF no formato 000.000.000-00 (opcional).",
                        max_length=14,
                        verbose_name="CPF",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proprietário",
                "verbose_name_plural": "Proprietários",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(
                        help_text="Data e horário do atendimento. Ex: 25/03/2026 14:00",
                        verbose_name="Data e horário",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("consulta", "Consulta"),
                            ("fisioterapia", "Fisioterapia"),
                            ("acupuntura", "Acupuntura"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de atendimento",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("agendado", "Agendado"),
                            ("confirmado", "Confirmado"),
                            ("realizado", "Realizado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="agendado",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        help_text="Informações adicionais sobre o atendimento (opcional).",
                        verbose_name="Observações",
                    ),
                ),
                (
                    "duracao_minutos",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Duração estimada do atendimento em minutos.",
                        verbose_name="Duração (minutos)",
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultas",
                        to="agendamentos.animal",
                        verbose_name="Animal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
                "ordering": ["data_hora"],
            },
        ),
        migrations.CreateModel(
            name="Disponibilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_da_semana",
                    models.IntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                        ],
                        verbose_name="Dia da semana",
                    ),
                ),
                (
                    "hora_inicio",
                    models.TimeField(
                        help_text="Horário de abertura da clínica. Ex: 08:00",
                        verbose_name="Início do atendimento",
                    ),
                ),
                (
                    "hora_fim",
                    models.TimeField(
                        help_text="Horário de encerramento da clínica. Ex: 19:00",
                        verbose_name="Fim do atendimento",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque para indicar que a clínica não atende neste dia.",
                        verbose_name="Ativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disponibilidade",
                "verbose_name_plural": "Disponibilidades",
                "ordering": ["dia_da_semana", "hora_inicio"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dia_da_semana",), name="unique_dia_da_semana"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="animal",
            name="proprietario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animais",
                to="agendamentos.proprietario",
                verbose_name="Proprietário",
            ),
        ),
    ]
